#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely.
# It also prints "I am invincible!!!" when receiving a SIGTERM signal.

for (( i=1; i>0; i++ ))
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
