#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely.
# It also prints "I am invincible!!!" when receiving a SIGTERM signal.

sigterm_handler() {
    echo "I am invincible!!!"
    exit 0
}

# Trap SIGTERM signal and call sigterm_handler function
trap 'sigterm_handler' SIGTERM

# Infinite loop with sleep 2 between each iteration
while true; do
    echo "To infinity and beyond"
    sleep 2
done
