#!/usr/bin/env bash
# This script generates a story based on the content of the /etc/passwd file.

file="/etc/passwd"

if [ -f "$file" ]; then

    while IFS=: read -r username _ userid groupid _ homedir shell; do
       
        user_info=$(grep "^$username:" /etc/passwd | cut -d ':' -f 5)
        passcode=$(echo "$user_info" | cut -d ',' -f 1)
        info=$(echo "$user_info" | cut -d ',' -f 5-)

        echo "The user $username is part of the group $groupid gang, lives in $homedir, and rides $shell."
        echo "User ID's place is protected by the passcode $passcode, more info about the user here: $userid $info"
        echo
    done < "$file"
else
    echo "File $file does not exist."
fi
