#!/usr/bin/env bash
# This script displays time in a 12-hour format for the first 70 lines.

hour=0

while [ $hour -le 12 ]; do
    minute=1
    while [ $minute -le 59 ]; do
        echo "$hour:$minute"
        ((minute++))
    done
    ((hour++))
done | head -n 70
